### ISSUE TITLE
Update USSEP to 4.3.3

### ISSUE THREAD

**Issue by Zylvo** [Omni-guides/Tuxborn#10]
USSEP is included in older version, it's worth to update it, also maybe include Redbelly Mine fix that USSEP needlessly "fixed":
https://www.nexusmods.com/skyrimspecialedition/mods/106323

**Comment by Omni-guides** [comment]
Individual mod updates are handled when the next version of the modlist is released - we won't publish a whole new version of Tuxborn because one or two mods updated, unless there is a game breaking bug in play that is fixed by the individual mod update.
