### ISSUE TITLE
Item descriptions while enchanting

### ISSUE THREAD

**Issue by hugo-brites** [Omni-guides/Tuxborn#6]
Hi,

 I'm trying Tuxborn 0.5.0-Preview3 [Desktop profile].

 While trying to enchant an item there is some text description added to the vanilla items. The issue is that while enchanting you no longer able to see the enchanting slider.

This doesn't happen with weapons or clothes/armors that don't have a description.

Vanilla item: 
![tux_vanilla_item](https://github.com/user-attachments/assets/a3c0e5f5-a50b-4f1b-97a6-4915773e178e)
Non Vanilla item:
![tux_non_vanilla_item](https://github.com/user-attachments/assets/95c65894-9075-430d-9e52-b4ddcf641c67)

If you try to enchant you get this screen:
![tux_vanilla_item_bar](https://github.com/user-attachments/assets/cbbeaca6-1ca6-4491-b75e-19d4f5f7b437)

As we can see the bar is there, just outside the normal view. It also doesn't behave properly. If you press left or right to change the enchant amplitude, it will only accept one input and will loose focus. 
You need to deselect the item and select it again to be able to move the slider one more time and after that repeat.

I've searched the discord and here but found no information about this

Thanks in advance for any help

**Comment by Ouruboros** [comment]
Already fixed in the proper release of 0.5 that will be here soon

**Comment by Ouruboros** [comment]
Remove Weapons Have Description if you can't wait

**Comment by Ouruboros** [comment]
@
